var arrayCharacters = [
    {
    "id": 1,
    "name": "Rick Sanchez",
    "status": "Alive",
    "species": "Human",
    "type": "",
    "gender": "Male",
    },
    {
    "id": 2,
    "name": "Morty Smith",
    "status": "Alive",
    "species": "Human",
    "type": "",
    "gender": "Male",
    },
    {
    "id": 3,
    "name": "Summer Smith",
    "status": "Alive",
    "species": "Human",
    "type": "",
    "gender": "Female",
    },
    {
    "id": 4,
    "name": "Beth Smith",
    "status": "Alive",
    "species": "Human",
    "type": "",
    "gender": "Female",
    },
    {
    "id": 5,
    "name": "Jerry Smith",
    "status": "Alive",
    "species": "Human",
    "type": "",
    "gender": "Male",
    },
    {
    "id": 6,
    "name": "Abadango Cluster Princess",
    "status": "Alive",
    "species": "Alien",
    "type": "",
    "gender": "Female",
    },
    {
    "id": 7,
    "name": "Abradolf Lincler",
    "status": "unknown",
    "species": "Human",
    "type": "Genetic experiment",
    "gender": "Male",
    },
    {
    "id": 8,
    "name": "Adjudicator Rick",
    "status": "Dead",
    "species": "Human",
    "type": "",
    "gender": "Male",
    },
    {
    "id": 9,
    "name": "Agency Director",
    "status": "Dead",
    "species": "Human",
    "type": "",
    "gender": "Male",
    },
    {
    "id": 10,
    "name": "Alan Rails",
    "status": "Dead",
    "species": "Human",
    "type": "Superhuman (Ghost trains summoner)",
    "gender": "Male",
    }
]